local_costmap:
   global_frame: map #odom
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   width: 10.0
   height: 10.0
   resolution: 0.05
   static_map: true #false
   rolling_window: false #true
